name: Python application test with Github Actions
# nothing 
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python --version: 3.10
    - name: Install dependencies
      run: |
        make install
    - name: lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
